import { model, Mongoose,Document } from "mongoose"

const mongoose=require("mongoose")

const StudentSchema=new mongoose.Schema({
    rollno:{type: String, required:true},
    branch:{type: String, required:true},
    sname:{type: String, required:true},
    created_at: {type:Date, required:true,default: new Date()},
    updated_at: {type:Date, required:true,default: new Date()},
    type: {type: String, required: true},
    phno:{type: String, required:true},
    email:{type: String, required:true},
    cname:{type: String, required:true},
    ccity:{type: String, required:true},
    password:{type: String, required:true},
    verified:{type:Boolean,required:true,default:false},
    verification_time:{type:Date,required:true,default:Date.now()+60000},
    trainLetter:{type: String },
    Fee:{type: String},
    GoalReport:{type: String},
    MidWayReport:{type: String},
    ReportFile:{type: String},
    ProjectPPT:{type: String},
    FinalLetter:{type: String},
    Arranged_by:{type:String},
    Mentor_name:{type:String},
    Mentor_email:{type:String},
    Stipend:{type:String},
    Mentor_Contact:{type:String},
    Cphno:{type:String},
    Country:{type:String},
    Address:{type:String},
    facassigned:{type:String},
    A1:{type:String},
    A2:{type:String},
    A3:{type:String},
    B1:{type:String},
    B2:{type:String},
    B3:{type:String},
    C1:{type:String},
    C2:{type:String},
    C3:{type:String},
    D1:{type:String},
    D2:{type:String},
    D3:{type:String},
    D4:{type:String},
    E1:{type:String},
    E2:{type:String},
    E3:{type:String},
    initTrainLetterEnable:{type:Boolean,required:true,default:false},
    goalReportEnable:{type:Boolean,required:true,default:false},
    midWayReportEnable:{type:Boolean,required:true,default:false},
    projectReportEnable:{type:Boolean,required:true,default:false},
    projectPPTEnable:{type:Boolean,required:true,default:false},
    finalTrainLetterEnable:{type:Boolean,required:true,default:false}
})
export interface StudentDoc extends Document
{
    rollno:String,
    branch:String,
    sname:String,
    created_at: Date,
    updated_at: Date,
    type: String,
    phno:String,
    email: String,
    cname: String,
    ccity: String,
    password: string,
    verified:Boolean,
    verification_time:Date,
    trainLetter:String,
    Fee:String,
    GoalReport:String,
    MidWayReport:String,
    ReportFile:String,
    ProjectPPT:String,
    FinalLetter:String,
    Arranged_by:String,
    Mentor_name:String,
    Mentor_email:String,
    Stipend:String,
    Mentor_Contact:String,
    Cphno:String,
    Country:String,
    Address:String,
    facassigned: String,
    A1:String,
    A2:String,
    A3:String,
    B1:String,
    B2:String,
    B3:String,
    C1:String,
    C2:String,
    C3:String,
    D1:String,
    D2:String,
    D3:String,
    D4:String,
    E1:String,
    E2:String,
    E3:String,
    initTrainLetterEnable:boolean,
    goalReportEnable:boolean,
    midWayReportEnable:boolean,
    projectReportEnable:boolean,
    projectPPTEnable:boolean,
    finalTrainLetterEnable:boolean
}

export default model<StudentDoc>("Student",StudentSchema)